workflows:
  android-release:
    name: Android Release

    environment:
      node: 22

    scripts:
      - npm install

      - |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-release:
    name: iOS Release

    environment:
      node: 22

    scripts:
      - npm install

      - |
          cd ios
          pod install

      - |
          cd ios

          PROJECT_NAME=$(find . -maxdepth 1 -name "*.xcodeproj" | head -n 1 | sed 's|./||' | sed 's|.xcodeproj||')

          xcodebuild \
            -project "${PROJECT_NAME}.xcodeproj" \
            -scheme "${PROJECT_NAME}" \
            -sdk iphoneos \
            -configuration Release \
            build

    artifacts:
      - ios/**/*.ipa